<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro [
	<!ELEMENT libro (capitulo*)>
	<!ELEMENT capitulo ( (titulo | contenido)+, resumen)>
	<!ELEMENT titulo (#PCDATA)>
	<!ELEMENT contenido (#PCDATA)>
	<!ELEMENT resumen (#PCDATA)>
]>
<!-- comprobar que valida prácticamente todo -->
<libro>
	<capitulo>
		<titulo>Capítulo A</titulo>
		<resumen>Resumen 1</resumen>
	</capitulo>
	<capitulo>
		<contenido>contenido Y</contenido>
		<resumen>Resumen 2</resumen>
	</capitulo>
	<capitulo>
		<titulo>Capítulo A</titulo>
		<contenido>contenido X</contenido>
		<resumen>Resumen 3</resumen>
	</capitulo>
	<capitulo>
	  <titulo>Capítulo B</titulo>
		<contenido>contenido Y</contenido>
	  <titulo>Capítulo C</titulo>
		<contenido>contenido Z</contenido>
	  <titulo>Capítulo D</titulo>
		<contenido>contenido T</contenido>
		<resumen>Resumen 4</resumen>
	</capitulo>
	<capitulo>
		<contenido>contenido W</contenido>
    <titulo>Capítulo W</titulo>
		<resumen>Resumen 5</resumen>
	</capitulo>
	<capitulo>
		<contenido>contenido W</contenido>
		<contenido>contenido Q</contenido>
    <contenido>contenido R</contenido>
    <titulo>Capítulo Q</titulo>
		<resumen>Resumen 6</resumen>
	</capitulo>
</libro> 