<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro [
	<!ELEMENT libro (capitulo*)>
	<!ELEMENT capitulo ( (titulo+, contenido+), resumen)>
	<!ELEMENT titulo (#PCDATA)>
	<!ELEMENT contenido (#PCDATA)>
	<!ELEMENT resumen (#PCDATA)>
]>
<libro>
	<capitulo>
		<titulo>Capítulo A</titulo>
		<contenido>contenido del Capítulo A</contenido>
		<resumen>Resumen 1</resumen>
	</capitulo>
	<capitulo>
		<titulo>Capítulo A</titulo>
		<contenido>contenido del Capítulo A</contenido>
		<contenido>más contenido del Capítulo A</contenido>
		<contenido>y más contenido del Capítulo A</contenido>
		<resumen>Resumen 1</resumen>
	</capitulo>
	<capitulo>
		<titulo>Titulo  X</titulo>
		<titulo>Titulo  Y</titulo>
		<titulo>Titulo  Z</titulo>
		<contenido>contenido Y</contenido>
    <resumen>Resumen 1</resumen>
	</capitulo>
	<capitulo>
		<titulo>Titulo  X</titulo>
		<titulo>Titulo  Y</titulo>
		<titulo>Titulo  Z</titulo>
		<contenido>contenido Y</contenido>
		<contenido>y más contenido del Capítulo Y</contenido>
		<resumen>Resumen 2</resumen>
	</capitulo>
</libro> 