=== eluiui/LMSXL/3º trimestre/trabajos/1º examen/CopyXMLgl/mensaje/mensajes2/mensajes.dtd
<!ELEMENT mensajes (mensaje)*>
<!ELEMENT mensaje (num_telefono , fecha_envio , hora_envio? , contenido_mensaje)>
<!ELEMENT num_telefono (#PCDATA)>
<!ELEMENT fecha_envio (dia , mes , aÃ±o)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT aÃ±o (#PCDATA)>
<!ELEMENT hora_envio (#PCDATA)>
<!ELEMENT contenido_mensaje (#PCDATA)>

=== eluiui/LMSXL/3º trimestre/trabajos/1º examen/CopyXMLgl/mensaje/mensajes2/mensajes2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mensajes SYSTEM "mensajes.dtd" [
]>
<mensajes>
  <mensaje>
    <num_telefono>999999999</num_telefono>
    <fecha_envio>
      <dia>1</dia>
      <mes>marzo</mes>
      <año>2023</año>
    </fecha_envio>
    <hora_envio>12:00</hora_envio>
    <contenido_mensaje>dfjghdhuisiadsbadhjs</contenido_mensaje>
  </mensaje>
  <mensaje>
    <num_telefono>666666666</num_telefono>
    <fecha_envio>
      <dia>1</dia>
      <mes>marzo</mes>
      <año>2023</año>
    </fecha_envio>
    <contenido_mensaje>QUEDISE</contenido_mensaje>
  </mensaje>
  <mensaje>
    <num_telefono>999999999</num_telefono>
    <fecha_envio>
      <dia>1</dia>
      <mes>marzo</mes>
      <año>2023</año>
    </fecha_envio>
    <hora_envio>12:10</hora_envio>
    <contenido_mensaje>nadaxdddd</contenido_mensaje>
  </mensaje>
</mensajes>
