=== eluiui/LMSXL/ciudades/ciudades.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="ciudades">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ciudad" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="provincia" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="comunidad" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="num_habitantes" type="xs:integer" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="CP" type="xs:string" use="optional"/>
            <xs:attribute name="patrimonio" type="xs:boolean" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== eluiui/LMSXL/3º trimestre/trabajos/2º examen/ciudades/ciudades.xml
<?xml version="1.0" encoding="UTF-8"?>
<ciudades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Z:/1º%20DAM/LMSXL/3º%20trimestre/trabajos/2º%20examen//ciudades/ciudades.xsd">
  <ciudad CP="36000" patrimonio="false">
    <nombre>Vigo</nombre>  
    <provincia>Pontevedra</provincia>
    <comunidad>Galicia</comunidad>
    <num_habitantes>300395</num_habitantes>
  </ciudad>
  <ciudad patrimonio="false">
    <nombre>Bueu</nombre>  
    <provincia>Pontevedra</provincia>
    <comunidad>Galicia</comunidad>
    <num_habitantes>11950</num_habitantes>
  </ciudad>
      <ciudad patrimonio="true">
    <nombre >Monforte</nombre>  
    <provincia>Lugo</provincia>
    <comunidad>Galicia</comunidad>
    <num_habitantes>18347</num_habitantes>
  </ciudad>
  <ciudad  patrimonio="false">
    <nombre>Valdemoro</nombre>  
    <provincia>Madrid</provincia>
    <comunidad>Madrid</comunidad>
    <num_habitantes>77270</num_habitantes>
  </ciudad>
    <ciudad patrimonio="true">
    <nombre>Badalona</nombre>  
    <provincia>Barcelona</provincia>
    <comunidad>Cataluña</comunidad>
    <num_habitantes>223166</num_habitantes>
  </ciudad>   
</ciudades>
