<?xml version="1.0" encoding="UTF-8"?>
<!-- RACION ES UN ELEMENTO MIXTO 
       OPCION MENOS RECOMENDABLE -->
       <!DOCTYPE alimentos [
<!ELEMENT alimentos (alimento)+>
<!ELEMENT alimento (nombre, racion, calorias, proteinas,grasas)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT racion (#PCDATA|unidad)*>
<!ELEMENT unidad (#PCDATA)>
<!ELEMENT calorias (#PCDATA)>
<!ELEMENT proteinas (#PCDATA)>
<!ELEMENT grasas (#PCDATA)>
]>
<alimentos>
  <alimento>
    <nombre>Pan</nombre>
    <racion>60
		    <unidad>gr</unidad>
	</racion>
    <calorias>153</calorias>
    <proteinas>4,2</proteinas>
    <grasas>0,5</grasas>
  </alimento>
  <alimento>
    <nombre>Leche</nombre>
    <racion>200
		    <unidad>gr</unidad>	
	</racion>
    <calorias>136</calorias>
    <proteinas>7</proteinas>
    <grasas>7.8</grasas>
  </alimento>
  <alimento>
    <nombre>Azúcar</nombre>
    <racion>15
		    <unidad>gr</unidad>
	</racion>
    <calorias>57</calorias>
    <proteinas>0</proteinas>
    <grasas>0</grasas>    
  </alimento>
  <alimento>
    <nombre>Lentejas</nombre>
    <racion>60
		<unidad>gr</unidad>
	</racion>
    <calorias>202</calorias>
    <proteinas>14.4</proteinas>
    <grasas>1</grasas>
  </alimento>
  <alimento>
    <nombre>Aceite</nombre>
    <racion>50
		    <unidad>ml</unidad>	
	</racion>
    <calorias>450</calorias>
    <proteinas>0</proteinas>    
    <grasas>50</grasas>
  </alimento>
  <alimento>
    <nombre>Melocotón</nombre>
    <racion>150
		    <unidad>gr</unidad>	
	</racion>
    <calorias>67</calorias>
    <proteinas>0.64</proteinas>
    <grasas>0.12</grasas>
  </alimento>
</alimentos>