=== eluiui/LMSXL/2º trimestre/trabajos/2º examen/CopyXMLgl/alumno/alumnos/alumnos.dtd
<!ELEMENT alumnos (alumno)*>
<!ELEMENT alumno (nombre , apellidos , DNI , fecha_nac , telefono? , curso , nombre_asignatura+)>
<!ATTLIST alumno codigo ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (apellido1 , apellido2)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT fecha_nac (dia , mes , año)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT curso (#PCDATA)>
<!ELEMENT nombre_asignatura (asignatura , nota)>
<!ELEMENT asignatura (#PCDATA)>
<!ELEMENT nota (#PCDATA)>

=== eluiui/LMSXL/CopyXMLgl/alumno/alumnos/alumnos_v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM "alumnos.dtd">
<alumnos>
  <alumno codigo="A001">
    <nombre>Marta</nombre>
    <apellidos>
      <apellido1>Perez</apellido1>
      <apellido2>Clavero</apellido2>
    </apellidos>
    <DNI>1010101O</DNI>
    <fecha_nac>
      <dia>1</dia>
      <mes>enero</mes>
      <año>1997</año>
    </fecha_nac>
    <curso>DAM</curso>
    <nombre_asignatura>
      <asignatura>Programacion</asignatura>
      <nota>8</nota>
    </nombre_asignatura>
  </alumno>
  <alumno codigo="B002">
    <nombre>Diego</nombre>
    <apellidos>
      <apellido1>Perez</apellido1>
      <apellido2>Clavero</apellido2>
    </apellidos>
    <DNI>1010101Z</DNI>
    <fecha_nac>
      <dia>1</dia>
      <mes>enero</mes>
      <año>1997</año>
    </fecha_nac>
    <telefono>123456789</telefono>
    <curso>DAM</curso>
    <nombre_asignatura>
      <asignatura>Programacion</asignatura>
      <nota>8</nota>
    </nombre_asignatura>
  </alumno>
    <alumno codigo="C003">
    <nombre>Pepe</nombre>
    <apellidos>
      <apellido1>Perez</apellido1>
      <apellido2>Clavero</apellido2>
    </apellidos>
    <DNI>1010101G</DNI>
    <fecha_nac>
      <dia>1</dia>
      <mes>enero</mes>
      <año>1997</año>
    </fecha_nac>
    <telefono>123456789</telefono>
    <curso>DAM</curso>
    <nombre_asignatura>
      <asignatura>Programacion</asignatura>
      <nota>8</nota>
    </nombre_asignatura>
        <nombre_asignatura>
      <asignatura>FOL</asignatura>
      <nota>8</nota>
    </nombre_asignatura>
  </alumno>
</alumnos>

=== eluiui/LMSXL/2º trimestre/trabajos/2º examen/CopyXMLgl/alumno/ALUMNOS2/alumnos_v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM "alumnos.dtd">
<alumnos>
  <alumno codigo="A001">
    <nombre>Marta</nombre>
    <apellidos>
      <apellido1>Perez</apellido1>
      <apellido2>Clavero</apellido2>
    </apellidos>
    <DNI>1010101O</DNI>
    <fecha_nac>
      <dia>1</dia>
      <mes>enero</mes>
      <año>1997</año>
    </fecha_nac>
    <curso nombre="DAW"/>
      <asignatura nombre="L.M." nota="8"/>
      <asignatura nombre="BB.DD." nota="8"/>
  </alumno>
  <alumno codigo="B002">
    <nombre>Diego</nombre>
    <apellidos>
      <apellido1>Perez</apellido1>
      <apellido2>Clavero</apellido2>
    </apellidos>
    <DNI>1010101Z</DNI>
    <fecha_nac>
      <dia>1</dia>
      <mes>enero</mes>
      <año>1997</año>
    </fecha_nac>
    <telefono>123456789</telefono>
    <curso nombre="DAM"/>
      <asignatura nombre="Redes" nota="8"/>
  </alumno>
    <alumno codigo="C003">
    <nombre>Pepe</nombre>
    <apellidos>
      <apellido1>Perez</apellido1>
      <apellido2>Clavero</apellido2>
    </apellidos>
    <DNI>1010101G</DNI>
    <fecha_nac>
      <dia>1</dia>
      <mes>enero</mes>
      <año>1997</año>
    </fecha_nac>
    <telefono>123456789</telefono>
    <curso nombre="DAM"/>
      <asignatura nombre="Redes" nota="8"/>
      <asignatura nombre="L.M." nota="8"/>
  </alumno>
  <alumno codigo="X004">
    <nombre>MARCOS</nombre>
    <apellidos>
      <apellido1>Perez</apellido1>
      <apellido2>Clavero</apellido2>
    </apellidos>
    <DNI>1010101P</DNI>
    <fecha_nac>
      <dia>1</dia>
      <mes>enero</mes>
      <año>1997</año>
    </fecha_nac>
    <telefono>123456782</telefono>
    <curso nombre="DAM"/>
      <asignatura nombre="Redes" nota="8"/>
      <asignatura nombre="L.M." nota="8"/>
      <asignatura nombre="BB.DD." nota="8"/>
  </alumno>
  </alumnos>
