<?xml version="1.0" encoding="UTF-8"?>
       <!DOCTYPE alimentos [
<!ELEMENT alimentos (alimento)+>
<!ELEMENT alimento (nombre, racion, calorias, proteinas,grasas)>
<!ATTLIST alimento clave ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT racion (#PCDATA)>
<!ATTLIST racion unidad CDATA #REQUIRED>
<!ELEMENT calorias (#PCDATA)>
<!ELEMENT proteinas (#PCDATA)>
<!ELEMENT grasas (#PCDATA)>
]>
<alimentos>
  <alimento clave="P100">
    <nombre>Pan</nombre>
    <racion unidad="gr">60</racion>
    <calorias>153</calorias>
    <proteinas>4,2</proteinas>
    <grasas>0,5</grasas>
  </alimento>
  <alimento clave="L101">
    <nombre>Leche</nombre>
    <racion unidad="gr">200</racion>
    <calorias>136</calorias>
    <proteinas>7</proteinas>
    <grasas>7.8</grasas>
  </alimento>
  <alimento clave="A102">
    <nombre>Azúcar</nombre>
    <racion unidad="gr">15</racion>
    <calorias>57</calorias>
    <proteinas>0</proteinas>
    <grasas>0</grasas>    
  </alimento>
  <alimento clave="L103">
    <nombre>Lentejas</nombre>
    <racion unidad="gr">60</racion>
    <calorias>202</calorias>
    <proteinas>14.4</proteinas>
    <grasas>1</grasas>
  </alimento>
  <alimento clave="A104">
    <nombre>Aceite</nombre>
    <racion unidad="ml">50</racion>
    <calorias>450</calorias>
    <proteinas>0</proteinas>    
    <grasas>50</grasas>
  </alimento>
  <alimento clave="M105">
    <nombre>Melocotón</nombre>
    <racion unidad="gr">150</racion>
    <calorias>67</calorias>
    <proteinas>0.64</proteinas>
    <grasas>0.12</grasas>
  </alimento>
</alimentos>