=== eluiui/LMSXL/clientes/clientes_v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="clientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cliente" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="dato">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="otro_dato">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="cif" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="empresa" type="xs:string"/>
              <xs:element name="localidad" type="xs:string"/>
              <xs:element name="provincia" type="xs:string"/>
              <xs:element name="facturacion" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== eluiui/LMSXL/3º trimestre/trabajos/2º examen/clientes/clientes_v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                  xsi:noNamespaceSchemaLocation="clientes_v2.xsd">
  <cliente>
    <dato>
      <otro_dato>
            <cif>X11111111</cif>
      </otro_dato>
    </dato>
    <empresa>Empresa XXXX</empresa>
    <localidad>Ponteareas</localidad>
    <provincia>PONTEVEDRA</provincia>
    <facturacion>24567.99</facturacion>
  </cliente>
  <cliente>
    <dato>
      <otro_dato>
            <cif>Z99999999</cif>
      </otro_dato>
    </dato>
    <empresa>Empresa ZZZZ</empresa>
    <localidad>Redondela</localidad>
    <provincia>PONTEVEDRA</provincia>
    <facturacion>2456700</facturacion>
  </cliente>
  <cliente>
    <dato>
      <otro_dato>
                <cif>Y33333333</cif>
      </otro_dato>
    </dato>  
    <empresa>Empresa YYYYY</empresa>
    <localidad>Moaña</localidad>
    <provincia>PONTEVEDRA</provincia>
    <facturacion>10000000</facturacion>
  </cliente>  
</clientes>
