=== eluiui/LMSXL/3º trimestre/trabajos/1º examen/CopyXMLgl/persona/personas3/personas.dtd
<!ENTITY % numeros  "CDATA">
  <!ENTITY % texto  "CDATA">
   <!ENTITY % obligatorio  "#REQUIRED">
  <!ELEMENT personas (persona*)>
  <!ELEMENT persona (nombre, localidad?, fecha_nacimiento)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT localidad (#PCDATA)>
  <!ELEMENT fecha_nacimiento EMPTY>
    <!ATTLIST fecha_nacimiento  
                      dia    %numeros   %obligatorio
                      mes  %texto  %obligatorio
                      ano   %numeros  %obligatorio>
                      
                      <!--EQUIVALE A -->


<!--  <!ELEMENT personas (persona*)>
  <!ELEMENT persona (nombre, localidad?, fecha_nacimiento)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT localidad (#PCDATA)>
  <!ELEMENT fecha_nacimiento EMPTY>
    <!ATTLIST fecha_nacimiento  
                      dia    CDATA  #REQUIRED
                      mes  CDATA  #REQUIRED
                      ano   CDATA  #REQUIRED>
                      
                      <!--EQUIVALE A -->-->

=== eluiui/LMSXL/3º trimestre/trabajos/1º examen/CopyXMLgl/persona/personas3/personas3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- entidades parametrizadas. -->
<!DOCTYPE personas SYSTEM "personas.dtd">
<personas>
  <persona>
    <nombre>Maria</nombre>  
    <localidad>Vigo</localidad>
    <fecha_nacimiento dia="12" mes="Marzo" ano="1988"/>
    <fecha_alta dia="1" mes="Abril" ano="2015"/>
  </persona>
  <persona>
    <nombre>Manuel</nombre>  
    <localidad>Pontevedra</localidad>
    <fecha_nacimiento dia="2" mes="Noviembre" ano="1980"/>
    <fecha_alta dia="30" mes="Enero" ano="2002"/>
  </persona>
  <persona>
    <nombre>Juan</nombre>  
    <localidad>Nigrán</localidad>
    <fecha_nacimiento dia="7" mes="Agosto" ano="1990"/>
    <fecha_alta dia="10" mes="Septiembre" ano="2014"/>
  </persona>
</personas>

=== eluiui/LMSXL/CopyXMLgl/persona/personas3/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- entidades parametrizadas. -->
<!DOCTYPE personas SYSTEM "personas.dtd">
<personas>
  <persona>
    <nombre>Maria</nombre>  
    <localidad>Vigo</localidad>
    <fecha_nacimiento dia="12" mes="Marzo" ano="1988"/>
  </persona>
  <persona>
    <nombre>Manuel</nombre>  
    <localidad>Pontevedra</localidad>
    <fecha_nacimiento dia="2" mes="Noviembre" ano="1980"/>
  </persona>
  <persona>
    <nombre>Juan</nombre>  
    <localidad>Nigrán</localidad>
    <fecha_nacimiento dia="7" mes="Agosto" ano="1990"/>
  </persona>
</personas>

=== eluiui/LMSXL/CopyXMLgl/persona/mas personas/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- entidades parametrizadas. Entidad dentro de otra -->
<!DOCTYPE personas SYSTEM "personas.dtd">
<personas>
  <persona>
    <nombre>Maria</nombre>  
    <localidad>Vigo</localidad>
    <fecha_nacimiento dia="12" mes="Marzo" ano="1988"/>
  </persona>
  <persona>
    <nombre>Manuel</nombre>  
    <localidad>C&amp;A</localidad>
    <fecha_nacimiento dia="2" mes="Noviembre" ano="1980"/>
  </persona>
      <persona>
    <nombre>Juan</nombre>  
    <localidad>Xunta de Galicia</localidad>
    <fecha_nacimiento dia="7" mes="Agosto" ano="1990"/>
  </persona>
</personas>
