<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE censo [
<!ELEMENT censo (persona)+>
<!ELEMENT persona (nombre,NIF,NIE, mujer,fecha-de-nacimiento, ciudad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mujer EMPTY>
<!ELEMENT fecha-de-nacimiento (dia, mes, año)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT NIE (#PCDATA)>
]>
<censo>
<persona>
<nombre>Elsa</nombre>
<NIF>1111111a</NIF>
<NIE>dufhwejkfh</NIE>
<mujer/>
<fecha-de-nacimiento>
<dia>18</dia>
<mes>6</mes>
<año>1996</año>
</fecha-de-nacimiento>
<ciudad>Pamplona</ciudad>
</persona>
<persona>
<nombre>Pepe</nombre>
<NIF>1191111a</NIF>
<NIE>dufh99jkfh</NIE>
<mujer/>
<fecha-de-nacimiento>
<dia>17</dia>
<mes>7</mes>
<año>1999</año>
</fecha-de-nacimiento>
<ciudad>Madrid</ciudad>
</persona>
</censo>