=== eluiui/LMSXL/proveedores/proveedores_productos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="proveedores_productos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="producto" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="codigo" type="xs:string"/>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="suministrado_por" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="proveedor" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="cif" type="xs:string"/>
              <xs:element name="empresa" type="xs:string"/>
              <xs:element name="localidad" type="xs:string"/>
              <xs:element name="provincia" type="xs:string"/>
              <xs:element name="facturacion" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    
    <xs:unique name="codigo_producto">
      <xs:selector xpath="proveedor"/>
      <xs:field xpath="cif"/>
    </xs:unique>
    
    <xs:key name="cif_proveedor">
      <xs:selector xpath="proveedor"/>
      <xs:field xpath="cif"/>
    </xs:key>
    
    <xs:keyref name="fk" refer="cif_proveedor">
      <xs:selector xpath="producto"/>
      <xs:field xpath="suministrado_por"/>
    </xs:keyref>
    
  </xs:element>
</xs:schema>

=== eluiui/LMSXL/proveedores/proveedores_productos.xml
<?xml version="1.0" encoding="UTF-8"?>
<proveedores_productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="proveedores_productos.xsd">
  <producto>
    <codigo>1111</codigo>
    <nombre>Folios</nombre>
    <suministrado_por>X111111111</suministrado_por>
  </producto>
  <producto>
    <codigo>2222</codigo>
    <nombre>Plastilina</nombre>
    <suministrado_por>X111111111</suministrado_por>
  </producto>
  <producto>
    <codigo>3333</codigo>
    <nombre>Agenda</nombre>
    <suministrado_por>Z999999999</suministrado_por>
  </producto>
  <producto>
    <codigo>4444</codigo>
    <nombre>Bolígrafo</nombre>
    <suministrado_por>Z999999999</suministrado_por>
  </producto>
  <producto>
    <codigo>5555</codigo>
    <nombre>Grapadora</nombre>
    <suministrado_por>Z999999999</suministrado_por>
  </producto>
  <proveedor>
    <cif>X11111111</cif>
    <empresa>Empresa XXXX</empresa>
    <localidad>Ponteareas</localidad>
    <provincia>PONTEVEDRA</provincia>
    <facturacion>24567.99</facturacion>
  </proveedor>
  <proveedor>
    <cif>Z99999999</cif>
    <empresa>Empresa ZZZZ</empresa>
    <localidad>Redondela</localidad>
    <provincia>PONTEVEDRA</provincia>
    <facturacion>2456700</facturacion>
  </proveedor>
  <proveedor>
    <cif>Y33333333</cif>
    <empresa>Empresa YYYYY</empresa>
    <localidad>Moaña</localidad>
    <provincia>PONTEVEDRA</provincia>
    <facturacion>10000000</facturacion>
  </proveedor>
</proveedores_productos>
