=== eluiui/LMSXL/mensajes/mensajes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="mensajes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="mensaje" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
         <xs:complexType>
           <xs:sequence>
             <xs:element name="num_telefono" type="xs:string" minOccurs="1" maxOccurs="1"/>
             <xs:element name="fecha_envio" type="xs:string" minOccurs="1" maxOccurs="1"/>
               <xs:complexType>
                 <xs:sequence>
                   <xs:element name="dia" type="xs:day" minOccurs="1" maxOccurs="1"/>
                   <xs:element name="mes" type="xs:string" minOccurs="1" maxOccurs="1"/>
                   <xs:element name="año" type="xs:year" minOccurs="1" maxOccurs="1"/>
                 </xs:sequence>
               </xs:complexType>
             <xs:element name="hora_envio" type="xs:datetime" minOccurs="0" maxOccurs="1"/>
             <xs:element name="contenido_mensaje" type="xs:string" minOccurs="1" maxOccurs="1"/>
           </xs:sequence>
         </xs:complexType>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== eluiui/LMSXL/mensajes/mensajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<mensajes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Z:/1º%20DAM/LMSXL/3º%20trimestre/trabajos/2º%20examen/mensajes/mensajes.xsd">
  <mensaje>
    <num_telefono>999999999</num_telefono>
    <fecha_envio>
      <dia>1</dia>
      <mes>marzo</mes>
      <año>2023</año>
    </fecha_envio>
    <hora_envio>12:00</hora_envio>
    <contenido_mensaje>dfjghdhuisiadsbadhjs</contenido_mensaje>
  </mensaje>
  <mensaje>
    <num_telefono>666666666</num_telefono>
    <fecha_envio>
      <dia>1</dia>
      <mes>marzo</mes>
      <año>2023</año>
    </fecha_envio>
    <contenido_mensaje>QUEDISE</contenido_mensaje>
  </mensaje>
  <mensaje>
    <num_telefono>999999999</num_telefono>
    <fecha_envio>
      <dia>1</dia>
      <mes>marzo</mes>
      <año>2023</año>
    </fecha_envio>
    <hora_envio>12:10</hora_envio>
    <contenido_mensaje>nadaxdddd</contenido_mensaje>
  </mensaje>
</mensajes>
