<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alimentos [
<!ELEMENT alimentos (distribuidor+,alimento+)>
<!ELEMENT distribuidor (marca, provincia,telefono)>
<!ATTLIST distribuidor clave ID #REQUIRED>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT alimento (nombre, racion, calorias, proteinas,grasas)>
<!ATTLIST alimento distribuye IDREF #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT racion (#PCDATA)>
<!ATTLIST racion unidad (gr|ml) #REQUIRED>
<!ELEMENT calorias (#PCDATA)>
<!ELEMENT proteinas (#PCDATA)>
<!ELEMENT grasas (#PCDATA)>
]>
<alimentos>
  <distribuidor clave="B001">
    <marca>Bimbo</marca>
    <provincia>Madrid</provincia>
    <telefono>91000111</telefono>
  </distribuidor>
  <distribuidor clave="D002">
    <marca>Danone</marca>
    <provincia>Barcelona</provincia>
    <telefono>92999999</telefono>
  </distribuidor>
   <alimento distribuye="B001">
    <nombre>Pan</nombre>
    <racion unidad="gr">60</racion>
    <calorias>153</calorias>
    <proteinas>4,2</proteinas>
    <grasas>0,5</grasas>
  </alimento>
  <alimento distribuye="D002">
    <nombre>Leche</nombre>
    <racion unidad="gr">200</racion>
    <calorias>136</calorias>
    <proteinas>7</proteinas>
    <grasas>7.8</grasas>
  </alimento>
  <alimento>
    <nombre>Azúcar</nombre>
    <racion unidad="gr">15</racion>
    <calorias>57</calorias>
    <proteinas>0</proteinas>
    <grasas>0</grasas>    
  </alimento>
  <alimento>
    <nombre>Lentejas</nombre>
    <racion unidad="gr">60</racion>
    <calorias>202</calorias>
    <proteinas>14.4</proteinas>
    <grasas>1</grasas>
  </alimento>
  <alimento>
    <nombre>Aceite</nombre>
    <racion unidad="ml">50</racion>
    <calorias>450</calorias>
    <proteinas>0</proteinas>    
    <grasas>50</grasas>
  </alimento>
  <alimento>
    <nombre>Melocotón</nombre>
    <racion unidad="gr">150</racion>
    <calorias>67</calorias>
    <proteinas>0.64</proteinas>
    <grasas>0.12</grasas>
  </alimento>
</alimentos>