<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro [
	<!ELEMENT libro (capitulo*)>
	<!ELEMENT capitulo ( #PCDATA | titulo | desarrollo |resumen  )*>
	<!ELEMENT titulo (#PCDATA)>
	<!ELEMENT desarrollo (#PCDATA)>
	<!ELEMENT resumen (#PCDATA)>
]>
<libro>
	<capitulo>Esta es un capitulo
		<titulo>capitulo 1 - Epígrafe 1</titulo>
		<desarrollo>Desarrollo del titulo 1</desarrollo>
		<resumen>Epílogo 1</resumen>
	</capitulo>
	<capitulo>Esta es otro capitulo
		<resumen>Epílogo 1</resumen>
		<titulo>capitulo 1 - Epígrafe 1</titulo>
		<titulo>capitulo 1 - Epígrafe 1</titulo>
		<desarrollo>Desarrollo del titulo 1</desarrollo>
		<resumen>Epílogo 1</resumen>
	</capitulo>
  <capitulo>
		<titulo>capitulo 2 - Epígrafe 1</titulo>
		<desarrollo>Desarrollo del titulo 1</desarrollo>
		Esta es otra capitulo
		<resumen>Epílogo 2</resumen>
	</capitulo>
  <capitulo> Y esta es 
		<titulo>capitulo 2 - Epígrafe 1</titulo>
		otra capitulo
		<desarrollo>Desarrollo del titulo 1</desarrollo>
		Esta es otra capitulo
		<resumen>Epílogo 2</resumen>
		más
	</capitulo>
</libro> 